In [1]:
from pathlib import Path
import pandas as pd

In [2]:
RESULTS_PATH = Path.cwd()

# Summary statistics of all result files

In [ ]:
def calculate_summary_stats(df: pd.DataFrame):
    return df.loc['total_return'].aggregate(['mean','std','min','max'])

mean    0.494044
std     0.135959
min     0.229975
max     0.825212
Name: total_return, dtype: float64

In [ ]:
# Summary statistics of all result files found in the current directory
result_files = [result_file for result_file in Path.glob(RESULTS_PATH, '*.xlsx')]
sumstat = pd.DataFrame(index=pd.Index(["mean","std","min","max"]), columns=[*map(lambda v: v.name, result_files)])
for result_file in result_files:
    results_df = pd.read_excel(result_file, index_col=0)
    sumstat.loc[:, result_file.name] = calculate_summary_stats(results_df)
sumstat

,TF_RA_MVSK_4moments_nonconvex.xlsx,TF_RA_LMoments_4moments_nonconvex.xlsx,TF_RA_TLMoments5-95_4moments_nonconvex.xlsx,TF_RA_TLMoments1-99_4moments_nonconvex.xlsx,TF_RA_TLMoments10-90_4moments_nonconvex.xlsx
mean,0.494044,0.509748,0.393767,0.447796,0.463586
std,0.135959,0.164795,0.155234,0.12357,0.13513
min,0.229975,0.157561,0.127283,0.269761,0.19203
max,0.825212,0.875433,0.79004,0.737445,0.7685

# Examine one specific result file

In [21]:
results_df = pd.read_excel(RESULTS_PATH / "TF_RA_MVSK_4moments_nonconvex.xlsx", index_col=0)
results_df

,MVSKRating_0,MVSKRating_1,MVSKRating_2,MVSKRating_3,MVSKRating_4,MVSKRating_5,MVSKRating_6,MVSKRating_7,MVSKRating_8,MVSKRating_9,...,MVSKRating_49,MVSKRating_50,MVSKRating_51,MVSKRating_52,MVSKRating_53,MVSKRating_54,MVSKRating_55,MVSKRating_56,MVSKRating_57,MVSKRating_58
start,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,...,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00,2010-05-13 00:00:00
end,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,...,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00
rf,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
total_return,0.419219,0.400528,0.427281,0.429922,0.386578,0.365688,0.393632,0.481521,0.638278,0.517393,...,0.668914,0.506462,0.401762,0.459665,0.432431,0.452668,0.479133,0.460662,0.353153,0.364421
cagr,0.023618,0.022714,0.024005,0.024131,0.022031,0.020997,0.022377,0.026555,0.033462,0.028194,...,0.034739,0.027698,0.022774,0.025538,0.024251,0.025209,0.026444,0.025585,0.02037,0.020934
max_drawdown,-0.256774,-0.25158,-0.266448,-0.275133,-0.267402,-0.276052,-0.285253,-0.27888,-0.285223,-0.308708,...,-0.254392,-0.249747,-0.250425,-0.258473,-0.254105,-0.256014,-0.270004,-0.266347,-0.25895,-0.264178
calmar,0.091981,0.090285,0.090092,0.087707,0.082391,0.076063,0.078447,0.095219,0.117318,0.091328,...,0.136558,0.110904,0.090941,0.098803,0.095437,0.098469,0.09794,0.096057,0.078664,0.079243
mtd,0.020206,0.022411,0.023084,0.021575,0.022865,0.024165,0.021835,0.02684,0.029137,0.040134,...,0.046214,0.032395,0.027051,0.032384,0.030599,0.037433,0.036652,0.0375,0.043668,0.042019
three_month,-0.088419,-0.08676,-0.074154,-0.070539,-0.09017,-0.084294,-0.066247,-0.075604,-0.062496,-0.096803,...,-0.052063,-0.056221,-0.054559,-0.053955,-0.048344,-0.054294,-0.057256,-0.052623,-0.091221,-0.070367
six_month,-0.045752,-0.043512,-0.030658,-0.035078,-0.053816,-0.049794,-0.027371,-0.022993,-0.007328,-0.055858,...,-0.00196,-0.006478,-0.006631,-0.004058,0.002015,-0.006198,0.001433,0.009115,-0.048701,-0.013737
ytd,-0.039664,-0.038125,-0.026549,-0.027463,-0.048273,-0.044813,-0.020895,-0.022522,-0.009043,-0.057815,...,-0.012607,-0.013637,-0.009307,-0.008256,-0.002865,-0.013927,-0.007761,0.001353,-0.05667,-0.027411
one_year,0.02473,0.02539,0.028515,0.004142,-0.005232,-0.002815,-0.017036,-0.008234,0.028832,-0.046523,...,0.098977,0.070403,0.050387,0.063996,0.057611,0.057364,0.058016,0.07472,0.022028,0.050038
three_year,0.049739,0.050691,0.048191,0.035071,0.037588,0.035823,0.019906,0.028728,0.049861,0.020235,...,0.096082,0.070314,0.058769,0.068765,0.063872,0.071267,0.071419,0.070686,0.0539,0.076676
five_year,0.053433,0.054165,0.057311,0.055455,0.052188,0.05374,0.043774,0.05042,0.06326,0.05282,...,0.099061,0.079406,0.071196,0.080654,0.074457,0.080944,0.078656,0.081297,0.072938,0.084064
ten_year,0.037088,0.037799,0.036212,0.036404,0.033219,0.031652,0.033744,0.040084,0.050596,0.042575,...,0.052544,0.041822,0.034345,0.03854,0.036586,0.038041,0.039916,0.038611,0.030701,0.031556
incep,0.023618,0.022714,0.024005,0.024131,0.022031,0.020997,0.022377,0.026555,0.033462,0.028194,...,0.034739,0.027698,0.022774,0.025538,0.024251,0.025209,0.026444,0.025585,0.02037,0.020934
daily_sharpe,0.340837,0.329947,0.336133,0.341497,0.337274,0.311438,0.32407,0.371733,0.455035,0.355602,...,0.510769,0.461888,0.381683,0.417379,0.412173,0.426855,0.417017,0.390992,0.330331,0.33896
daily_sortino,0.473533,0.458452,0.466715,0.468862,0.459463,0.42264,0.446102,0.511068,0.634783,0.486808,...,0.704497,0.625597,0.514053,0.562762,0.561622,0.582101,0.570277,0.535373,0.446938,0.457276
daily_mean,0.02533,0.024463,0.025905,0.025942,0.023496,0.022767,0.024184,0.028224,0.034731,0.030592,...,0.035411,0.028284,0.023697,0.026375,0.025,0.025906,0.027386,0.026764,0.021641,0.022168
daily_vol,0.074318,0.074141,0.077068,0.075966,0.069665,0.073102,0.074624,0.075927,0.076326,0.08603,...,0.069329,0.061235,0.062084,0.063191,0.060655,0.06069,0.06567,0.068451,0.065512,0.0654
daily_skew,-1.750428,-1.727171,-1.747404,-2.049654,-2.109327,-2.177793,-1.998333,-2.204952,-1.83558,-2.13341,...,-1.891266,-2.396564,-2.539861,-2.603175,-2.170582,-2.039224,-1.956678,-1.911979,-2.011516,-2.099761
daily_kurt,19.700745,19.404027,23.423948,26.39673,23.534217,25.76441,25.011025,31.162612,27.376216,28.688798,...,35.995434,41.405605,41.935941,45.402561,34.880728,31.508366,34.608385,37.353286,30.323887,32.243373
best_day,0.042324,0.041221,0.050575,0.048009,0.036555,0.042423,0.040416,0.047196,0.048827,0.050037,...,0.05199,0.044202,0.041302,0.044782,0.035712,0.034836,0.044802,0.05281,0.041626,0.04159
worst_day,-0.056617,-0.057906,-0.065706,-0.067332,-0.058742,-0.063867,-0.068868,-0.072045,-0.072894,-0.079691,...,-0.060595,-0.063314,-0.065633,-0.067312,-0.060442,-0.057803,-0.06493,-0.068806,-0.059727,-0.062713
monthly_sharpe,0.308038,0.298571,0.315444,0.314822,0.290819,0.280873,0.283236,0.335209,0.399797,0.322606,...,0.50613,0.436988,0.370639,0.401854,0.391283,0.390674,0.367751,0.357744,0.294854,0.298513
monthly_sortino,0.488465,0.470834,0.49471,0.493131,0.451177,0.436392,0.438057,0.525852,0.634217,0.48951,...,0.837741,0.697681,0.584633,0.63455,0.609729,0.60396,0.55813,0.554561,0.43993,0.453702
monthly_mean,0.027269,0.026365,0.02755,0.02775,0.025727,0.024652,0.026574,0.030345,0.037317,0.03315,...,0.036821,0.029641,0.024762,0.027591,0.026223,0.027371,0.029305,0.028441,0.023311,0.023952
monthly_vol,0.088525,0.088303,0.087338,0.088145,0.088463,0.08777,0.093823,0.090526,0.093339,0.102758,...,0.07275,0.06783,0.066808,0.068659,0.067018,0.070061,0.079686,0.079502,0.079061,0.080237
monthly_skew,-0.179531,-0.19177,-0.292303,-0.358101,-0.422589,-0.425113,-0.616397,-0.539902,-0.424874,-0.66728,...,-0.004398,-0.231473,-0.270107,-0.281446,-0.324818,-0.384199,-0.451752,-0.267559,-0.510697,-0.351117
monthly_kurt,2.703695,2.486426,2.774828,3.635558,3.335498,3.573555,4.160546,4.418737,4.428039,3.642282,...,4.48534,4.835044,4.562741,5.296113,5.580918,5.8485,7.236588,6.446859,5.233107,5.511575
best_month,0.108792,0.106087,0.101067,0.10555,0.100676,0.098095,0.092761,0.09707,0.110623,0.090845,...,0.090108,0.075133,0.070109,0.075259,0.075366,0.077023,0.104877,0.101703,0.083135,0.090418
worst_month,-0.095035,-0.089869,-0.098899,-0.112292,-0.111519,-0.114765,-0.133286,-0.128243,-0.126431,-0.137183,...,-0.084355,-0.086628,-0.086794,-0.092087,-0.088687,-0.094775,-0.113319,-0.109385,-0.099747,-0.10345
yearly_sharpe,0.314774,0.299925,0.322012,0.330061,0.275568,0.26372,0.260516,0.308454,0.358817,0.284707,...,0.418451,0.381535,0.332646,0.365174,0.36212,0.343156,0.331602,0.326844,0.247065,0.252775
yearly_sortino,0.771477,0.693131,0.75873,0.802073,0.6424,0.623974,0.522204,0.62121,0.755969,0.579204,...,1.102999,0.93974,0.750555,0.936811,0.807158,0.779957,0.61156,0.608038,0.466238,0.471238
yearly_mean,0.026872,0.026127,0.0272,0.027129,0.025975,0.024943,0.027301,0.031171,0.03869,0.035064,...,0.038444,0.030541,0.025368,0.028148,0.026685,0.028225,0.030374,0.029339,0.025145,0.025735
yearly_vol,0.08537,0.087112,0.084469,0.082194,0.094258,0.094582,0.104797,0.101056,0.107827,0.123159,...,0.091872,0.080048,0.076261,0.077081,0.07369,0.082253,0.091597,0.089764,0.101774,0.101811
yearly_skew,0.477978,0.336186,0.426024,0.641204,0.623625,0.768548,0.466657,0.234909,0.206149,0.164172,...,0.609861,0.597407,0.649903,0.909469,0.506887,0.569225,-0.414741,-0.309317,0.050454,-0.025896
yearly_kurt,-0.069909,-0.249653,0.210329,0.70317,0.692292,1.01247,1.62944,1.194048,1.042708,0.475364,...,0.641799,1.087326,2.187948,1.914793,2.067561,1.709353,1.703569,1.710585,1.702289,1.900519
best_year,0.198181,0.195148,0.197109,0.201276,0.235306,0.239683,0.26678,0.252667,0.27407,0.270559,...,0.215879,0.205476,0.207343,0.213795,0.19922,0.214666,0.188725,0.191505,0.236563,0.228157
worst_year,-0.119453,-0.123688,-0.123704,-0.109549,-0.132838,-0.13348,-0.164422,-0.155879,-0.167189,-0.204323,...,-0.135303,-0.126106,-0.131237,-0.116668,-0.128213,-0.140462,-0.192755,-0.186878,-0.205129,-0.211696
avg_drawdown,-0.026018,-0.02645,-0.023268,-0.026903,-0.023285,-0.025152,-0.023077,-0.023556,-0.021788,-0.02053,...,-0.015837,-0.014262,-0.018327,-0.014674,-0.016831,-0.015583,-0.020133,-0.022135,-0.021,-0.02226
avg_drawdown_days,64.111111,59.842105,55.836066,62.444444,53.516129,54.9,55.20339,52.112903,40.282051,44.126761,...,24.74026,26.109589,34.303571,25.438356,28.123077,25.942029,29.048387,31.875,31.357143,34.039216
avg_up_month,0.022501,0.022119,0.0223,0.022826,0.023188,0.022713,0.026095,0.025827,0.025553,0.02711,...,0.026174,0.024765,0.024524,0.025258,0.023759,0.024689,0.02727,0.028346,0.026849,0.029254
avg_down_month,-0.01251,-0.012696,-0.011993,-0.011683,-0.011885,-0.011718,-0.011945,-0.01096,-0.011173,-0.013097,...,-0.005574,-0.005183,-0.005203,-0.005129,-0.005006,-0.005189,-0.005834,-0.005783,-0.006115,-0.006044
win_year_perc,0.466667,0.466667,0.466667,0.466667,0.466667,0.466667,0.533333,0.533333,0.533333,0.533333,...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.4,0.333333,0.266667
twelve_month_win_perc,0.476471,0.482353,0.482353,0.464706,0.464706,0.441176,0.458824,0.482353,0.494118,0.429412,...,0.352941,0.335294,0.329412,0.335294,0.323529,0.329412,0.311765,0.294118,0.258824,0.252941